// <auto-generated />
namespace MyVidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixGenres1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixGenres1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802021545180_fixGenres1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
